[package]
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
name                 = "berry-dump-bin"
repository.workspace = true
version.workspace    = true

publish = false

[dependencies]
berry-core = { workspace = true }
clap       = { workspace = true }
