[package]
authors.workspace    = true
categories.workspace = true
edition.workspace    = true
license.workspace    = true
name                 = "berry-core"
repository.workspace = true
version              = "0.2.0"

[dependencies]
nom = { workspace = true }

[lints]
workspace = true
