[package]
authors.workspace    = true
categories.workspace = true
edition.workspace    = true
license.workspace    = true
name                 = "berry-core"
repository.workspace = true
version              = "0.1.0"

[dependencies]
nom = "8.0.0"

[lints]
workspace = true
